### ISSUE TITLE
More PB issues...

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

The pathbuilder script?

### Priority

High

### Bug Description

Tried it once again, after pulling the latest updates, and now I got this:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    $ setup()
  File "game/script.rpy", line 17, in <module>
    $ setup()
NameError: name 'setup' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    $ setup()
  File "D:\renpy\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 17, in <module>
    $ setup()
NameError: name 'setup' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23042213
```

### Additional context

Ignoring it will lead to this:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    call screen path_builder_starting_location
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 8, in execute
    screen path_builder_starting_location():
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 8, in execute
    screen path_builder_starting_location():
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 15, in execute
    python:
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 17, in <module>
    if has_ep2():
NameError: name 'has_ep2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    call screen path_builder_starting_location
  File "D:\renpy\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "D:\renpy\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\renpy\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "D:\renpy\renpy\exports.py", line 3336, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "D:\renpy\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy\renpy\display\core.py", line 3499, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy\renpy\display\core.py", line 3969, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "D:\renpy\renpy\display\core.py", line 3969, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "D:\renpy\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 8, in execute
    screen path_builder_starting_location():
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 8, in execute
    screen path_builder_starting_location():
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 15, in execute
    python:
  File "game/screens/path_builder/path_builder_starting_location_screen.rpy", line 17, in <module>
    if has_ep2():
NameError: name 'has_ep2' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23042213
```

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
fixed in latest

**Comment by nfaStefan** [comment]
I pulled the latest changes, and I'm still getting these two.

**Comment by nfaStefan** [comment]
Yeah, to correct myself: ignoring it would lead to a different markdown (but to the same problem):

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/scene_gallery/scene_gallery_screen.rpy", line 86, in script
    $ SceneGallery.create_gallery()
  File "game/screens/scene_gallery/scene_gallery_screen.rpy", line 86, in <module>
    $ SceneGallery.create_gallery()
AttributeError: 'StoreModule' object has no attribute 'has_ep2'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/scene_gallery/scene_gallery_screen.rpy", line 86, in script
    $ SceneGallery.create_gallery()
  File "D:\renpy\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/screens/scene_gallery/scene_gallery_screen.rpy", line 86, in <module>
    $ SceneGallery.create_gallery()
  File "game/screens/scene_gallery/SceneGallery_ren.py", line 153, in create_gallery
    if store.has_ep2():
AttributeError: 'StoreModule' object has no attribute 'has_ep2'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23042213
```

**Comment by KiloOscarSix** [comment]
Fixed in latest
