### ISSUE TITLE
Getting no target relationship

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

Phone script?

### Priority

High

### Bug Description

I know it happens in CK2 aswell, but better be safe and sorry. It's regarding the relationships app:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/v1/v1.rpy", line 327, in script
    u "Alright, let me grab my bag and I'm ready."
  File "game/phone/phone_relationships.rpy", line 1, in execute
    screen relationships_home():
  File "game/phone/phone_relationships.rpy", line 1, in execute
    screen relationships_home():
  File "game/phone/phone_relationships.rpy", line 5, in execute
    use base_phone_rotated:
  File "game/phone/phone_screens.rpy", line 48, in execute
    screen base_phone_rotated():
  File "game/phone/phone_screens.rpy", line 48, in execute
    screen base_phone_rotated():
  File "game/phone/phone_screens.rpy", line 61, in execute
    frame:
  File "game/phone/phone_screens.rpy", line 66, in execute
    transclude
  File "game/phone/phone_relationships.rpy", line 5, in execute
    use base_phone_rotated:
  File "game/phone/phone_relationships.rpy", line 6, in execute
    frame:
  File "game/phone/phone_relationships.rpy", line 9, in execute
    vpgrid:
  File "game/phone/phone_relationships.rpy", line 18, in execute
    for character in (
  File "game/phone/phone_relationships.rpy", line 34, in execute
    frame:
  File "game/phone/phone_relationships.rpy", line 39, in execute
    hbox:
  File "game/phone/phone_relationships.rpy", line 44, in execute
    vbox:
  File "game/phone/phone_relationships.rpy", line 49, in execute
    if CharacterService.is_ex(character):
  File "game/phone/phone_relationships.rpy", line 60, in execute
    text CharacterService.get_relationship(character).name.capitalize():
  File "game/phone/phone_relationships.rpy", line 60, in <module>
    text CharacterService.get_relationship(character).name.capitalize():
TypeError: get_relationship() missing 1 required positional argument: 'target'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/v1/v1.rpy", line 327, in script
    u "Alright, let me grab my bag and I'm ready."
  File "D:\renpy\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy\renpy\exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "D:\renpy\renpy\character.py", line 1348, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy\renpy\character.py", line 999, in do_display
    display_say(who,
  File "D:\renpy\renpy\character.py", line 689, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\renpy\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy\renpy\display\core.py", line 3499, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy\renpy\display\core.py", line 3969, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\core.py", line 605, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "D:\renpy\renpy\display\core.py", line 3969, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "D:\renpy\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/phone/phone_relationships.rpy", line 1, in execute
    screen relationships_home():
  File "game/phone/phone_relationships.rpy", line 1, in execute
    screen relationships_home():
  File "game/phone/phone_relationships.rpy", line 5, in execute
    use base_phone_rotated:
  File "game/phone/phone_screens.rpy", line 48, in execute
    screen base_phone_rotated():
  File "game/phone/phone_screens.rpy", line 48, in execute
    screen base_phone_rotated():
  File "game/phone/phone_screens.rpy", line 61, in execute
    frame:
  File "game/phone/phone_screens.rpy", line 66, in execute
    transclude
  File "game/phone/phone_relationships.rpy", line 5, in execute
    use base_phone_rotated:
  File "game/phone/phone_relationships.rpy", line 6, in execute
    frame:
  File "game/phone/phone_relationships.rpy", line 9, in execute
    vpgrid:
  File "game/phone/phone_relationships.rpy", line 18, in execute
    for character in (
  File "game/phone/phone_relationships.rpy", line 34, in execute
    frame:
  File "game/phone/phone_relationships.rpy", line 39, in execute
    hbox:
  File "game/phone/phone_relationships.rpy", line 44, in execute
    vbox:
  File "game/phone/phone_relationships.rpy", line 49, in execute
    if CharacterService.is_ex(character):
  File "game/phone/phone_relationships.rpy", line 60, in execute
    text CharacterService.get_relationship(character).name.capitalize():
  File "game/phone/phone_relationships.rpy", line 60, in <module>
    text CharacterService.get_relationship(character).name.capitalize():
TypeError: get_relationship() missing 1 required positional argument: 'target'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23042213
```

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
fixed

**Comment by nfaStefan** [comment]
I'm still getting it, everytime I open the relationships app.
